#  __         ______     ______     ______
# /\ \       /\  ___\   /\  __ \   /\  ___\
# \ \ \____  \ \  __\   \ \  __ \  \ \  __\
#  \ \_____\  \ \_____\  \ \_\ \_\  \ \_\
#   \/_____/   \/_____/   \/_/\/_/   \/_/
#
# Author : Smudge
#
# Changing these values requires a proxy restart.
# Enable the database?
enabled: true
# Debug mode will output to console the
# databases procsesses.
debugmode: false

# ---------------------------------------
#             ✜ Database Type ✜
# ---------------------------------------
# SQLITE DATABASE
# This type of database saves the data
# to a file located in this folder.
type: SQLITE

# # MONGO DATABASE
# # This type of database saves data to the cloud.
#
# type: MONGO
# connection_string: "connectionString"
# database_name: "Leaf"

# # MYSQL DATABASE
# # This type of database saves data on an
# # external server or the cloud.
#
# type: MYSQL
# connection_string: "connectionString"

# ---------------------------------------
#             ✜ Settings ✜
# ---------------------------------------
# The maximum amount of history that will
# be saved in the database per player.
player_history_limit: 20

# The maximum number of messages that will
# be saved in the database per player.
message_limit: 100