#  __         ______     ______     ______
# /\ \       /\  ___\   /\  __ \   /\  ___\
# \ \ \____  \ \  __\   \ \  __ \  \ \  __\
#  \ \_____\  \ \_____\  \ \_\ \_\  \ \_\
#   \/_____/   \/_____/   \/_/\/_/   \/_/
#
# Author : Smudge
# File: database.yml
# Description: Contains the database settings.
#
# ⚠ Changing these values requires a proxy restart. ⚠

enabled: true

# Debug mode will output to console the
# databases procsesses.
debugmode: false

# ---------------------------------------
#           ✜ Database Type ✜
# ---------------------------------------
# This type of database saves the data
# to a file located in this folder.
sqlite:
  enable: true

# This type of database saves data to the cloud.
mongo:
  enable: false
  connection_string: "connectionString"
  database_name: "Leaf"

# This type of database saves data on an
# external server or the cloud.
mysql:
  enable: false
  connection_string: "address:port"
  database_name: "Leaf"
  username: ""
  password: ""

# ---------------------------------------
#             ✜ Settings ✜
# ---------------------------------------
# The maximum amount of history that will
# be saved in the database per player.
player_history_limit: 20

# The maximum number of messages that will
# be saved in the database per player.
message_limit: 100